export enum Permission {
  USERS_READ = 'users.read',
  USERS_UPDATE = 'users.update',
  USERS_DELETE = 'users.delete',
  USERS_ROLE_UPDATE = 'users.role.update',
  LISTINGS_MANAGE = 'listings.manage',
  DEALS_MANAGE = 'deals.manage',
  WALLET_APPROVE = 'wallet.approve',
  WALLET_REJECT = 'wallet.reject',
  WALLET_VIEW = 'wallet.view',
  SUPPORT_MANAGE = 'support.manage',
  TENANTS_MANAGE = 'tenants.manage',
  SUBSCRIPTIONS_MANAGE = 'subscriptions.manage',
  FINANCE_VIEW = 'finance.view',
  FINANCE_EXPORT = 'finance.export',
  AUDIT_VIEW = 'audit.view',
  ANALYTICS_VIEW = 'analytics.view',
  SYSTEM_MONITOR = 'system.monitor',
}